apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: learn
  name: postgres-persistent-volume
  labels:
    type: ebs
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: learn
  name: postgres-pv-claim
  labels:
    app : postgres
spec:
 storageClassName: manual
 accessModes:
   - ReadWriteMany
 resources:
    requests:
      storage : 5Gi
